// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-students.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^4.6.2";

// src/lib/mcp/tool-utils.ts
import { ToolError } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function projectUrl() {
  const value = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!value) throw new Error("SUPABASE_URL is required");
  return value;
}
function publishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const value = [keys.default, ...Object.values(keys)].find(
          (item) => typeof item === "string" && item.trim().startsWith("sb_publishable_")
        );
        if (value) return value.trim();
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (!legacy) throw new Error("A Supabase publishable key is required");
  return legacy;
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Authenticated MCP access is required");
  return createClient(projectUrl(), publishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tool-utils.ts
function textResult(value) {
  return {
    content: [{ type: "text", text: JSON.stringify(value, null, 2) }],
    structuredContent: value
  };
}
async function requireAdmin(ctx) {
  if (!ctx.isAuthenticated()) throw new ToolError("Fa\xE7a login para usar esta ferramenta.");
  const userId = ctx.getUserId();
  if (!userId) throw new ToolError("N\xE3o foi poss\xEDvel identificar o usu\xE1rio.");
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("user_roles").select("role").eq("user_id", userId).eq("role", "admin").maybeSingle();
  if (error || !data) throw new ToolError("Esta a\xE7\xE3o \xE9 exclusiva para administradores.");
  return supabase;
}
function databaseError(message) {
  return new ToolError(`N\xE3o foi poss\xEDvel concluir a opera\xE7\xE3o: ${message}`);
}

// src/lib/mcp/tools/list-students.ts
var list_students_default = defineTool({
  name: "list_students",
  title: "Listar alunos",
  description: "Lista os alunos vis\xEDveis para o usu\xE1rio conectado, com filtro opcional por nome.",
  inputSchema: { query: z.string().optional().describe("Parte do nome do aluno ou respons\xE1vel.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("students").select("id,student_name,guardian_name,address").order("student_name").limit(50);
    if (query?.trim()) request = request.or(`student_name.ilike.%${query.trim()}%,guardian_name.ilike.%${query.trim()}%`);
    const { data, error } = await request;
    if (error) throw databaseError(error.message);
    return textResult({ students: data ?? [] });
  }
});

// src/lib/mcp/tools/list-teachers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
var list_teachers_default = defineTool2({
  name: "list_teachers",
  title: "Listar professores",
  description: "Lista os professores ativos e seus identificadores de agenda.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const { data, error } = await supabaseForUser(ctx).from("teachers").select("id,name,active").eq("active", true).order("name");
    if (error) throw databaseError(error.message);
    const teachers = (data ?? []).map((teacher) => ({
      ...teacher,
      slug: teacher.name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/\s+/g, "-")
    }));
    return textResult({ teachers });
  }
});

// src/lib/mcp/tools/list-lessons.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^4.6.2";
var list_lessons_default = defineTool3({
  name: "list_lessons",
  title: "Consultar aulas",
  description: "Consulta aulas vis\xEDveis ao usu\xE1rio conectado dentro de um per\xEDodo.",
  inputSchema: {
    from: z2.string().describe("Data/hora inicial em ISO 8601."),
    to: z2.string().describe("Data/hora final em ISO 8601."),
    studentName: z2.string().optional(),
    teacher: z2.string().optional().describe("Identificador do professor, como thiago ou mayara."),
    status: z2.string().optional().describe("Situa\xE7\xE3o da aula, como agendada, realizada ou cancelada.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, studentName, teacher, status }, ctx) => {
    let request = supabaseForUser(ctx).from("lessons").select("*").gte("start_at", from).lt("start_at", to).order("start_at").limit(200);
    if (studentName) request = request.ilike("student_name", `%${studentName}%`);
    if (teacher) request = request.eq("teacher", teacher);
    if (status) request = request.eq("status", status);
    const { data, error } = await request;
    if (error) throw databaseError(error.message);
    return textResult({ lessons: data ?? [] });
  }
});

// src/lib/mcp/tools/create-lesson.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^4.6.2";
var create_lesson_default = defineTool4({
  name: "create_lesson",
  title: "Criar aula",
  description: "Cria uma aula ap\xF3s o usu\xE1rio confirmar aluno, professor, hor\xE1rio, dura\xE7\xE3o e valor por hora.",
  inputSchema: {
    studentName: z3.string(),
    guardianName: z3.string().optional(),
    teacher: z3.string(),
    startAt: z3.string(),
    durationMinutes: z3.number(),
    subject: z3.string().optional(),
    hourlyPrice: z3.number(),
    packageType: z3.string().optional(),
    isOnline: z3.boolean().optional(),
    address: z3.string().optional(),
    notes: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const supabase = await requireAdmin(ctx);
    const { data, error } = await supabase.from("lessons").insert({
      student_name: input.studentName,
      guardian_name: input.guardianName ?? null,
      teacher: input.teacher,
      start_at: input.startAt,
      duration_minutes: input.durationMinutes,
      subject: input.subject ?? null,
      price: input.hourlyPrice,
      package_type: input.packageType ?? "avulsa",
      is_online: input.isOnline ?? false,
      address: input.address ?? null,
      notes: input.notes ?? null
    }).select().single();
    if (error) throw databaseError(error.message);
    return textResult({ lesson: data });
  }
});

// src/lib/mcp/tools/update-lesson.ts
import { defineTool as defineTool5, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^4.6.2";
var update_lesson_default = defineTool5({
  name: "update_lesson",
  title: "Atualizar aula",
  description: "Atualiza os campos informados de uma aula existente ap\xF3s confirma\xE7\xE3o do usu\xE1rio.",
  inputSchema: {
    lessonId: z4.string(),
    studentName: z4.string().optional(),
    guardianName: z4.string().optional(),
    teacher: z4.string().optional(),
    startAt: z4.string().optional(),
    durationMinutes: z4.number().optional(),
    subject: z4.string().optional(),
    hourlyPrice: z4.number().optional(),
    isOnline: z4.boolean().optional(),
    address: z4.string().optional(),
    status: z4.string().optional(),
    paymentStatus: z4.string().optional(),
    notes: z4.string().optional(),
    classSummary: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ lessonId, ...input }, ctx) => {
    const supabase = await requireAdmin(ctx);
    const fields = Object.fromEntries(Object.entries({
      student_name: input.studentName,
      guardian_name: input.guardianName,
      teacher: input.teacher,
      start_at: input.startAt,
      duration_minutes: input.durationMinutes,
      subject: input.subject,
      price: input.hourlyPrice,
      is_online: input.isOnline,
      address: input.address,
      status: input.status,
      payment_status: input.paymentStatus,
      notes: input.notes,
      class_summary: input.classSummary
    }).filter(([, value]) => value !== void 0));
    if (Object.keys(fields).length === 0) throw new ToolError2("Informe ao menos um campo para atualizar.");
    const { data, error } = await supabase.from("lessons").update(fields).eq("id", lessonId).select().single();
    if (error) throw databaseError(error.message);
    return textResult({ lesson: data });
  }
});

// src/lib/mcp/tools/delete-lesson.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z5 } from "npm:zod@^4.6.2";
var delete_lesson_default = defineTool6({
  name: "delete_lesson",
  title: "Excluir aula",
  description: "Exclui definitivamente uma aula ap\xF3s confirma\xE7\xE3o expl\xEDcita do usu\xE1rio.",
  inputSchema: { lessonId: z5.string() },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lessonId }, ctx) => {
    const { error } = await (await requireAdmin(ctx)).from("lessons").delete().eq("id", lessonId);
    if (error) throw databaseError(error.message);
    return textResult({ deleted: true, lessonId });
  }
});

// src/lib/mcp/tools/wallet.ts
import { defineTool as defineTool7, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z6 } from "npm:zod@^4.6.2";
var getWalletBalance = defineTool7({
  name: "get_wallet_balance",
  title: "Consultar saldo",
  description: "Consulta saldo e lan\xE7amentos financeiros vis\xEDveis ao usu\xE1rio conectado.",
  inputSchema: { studentName: z6.string().optional(), guardianName: z6.string().optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ studentName, guardianName }, ctx) => {
    let request = supabaseForUser(ctx).from("wallet_transactions").select("*").order("created_at", { ascending: false }).limit(100);
    if (guardianName) request = request.eq("guardian_name", guardianName);
    else if (studentName) request = request.ilike("student_name", `%${studentName}%`);
    const { data, error } = await request;
    if (error) throw databaseError(error.message);
    const rows = data ?? [];
    return textResult({ balance: rows.reduce((sum, row) => sum + Number(row.amount), 0), transactions: rows });
  }
});
var addWalletCredit = defineTool7({
  name: "add_wallet_credit",
  title: "Registrar cr\xE9dito",
  description: "Registra um pagamento ou ajuste positivo ap\xF3s confirma\xE7\xE3o do usu\xE1rio.",
  inputSchema: { studentName: z6.string(), guardianName: z6.string().optional(), amount: z6.number(), kind: z6.string().optional(), description: z6.string().optional() },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ studentName, guardianName, amount, kind, description }, ctx) => {
    if (amount <= 0) throw new ToolError3("O valor do cr\xE9dito deve ser positivo.");
    const supabase = await requireAdmin(ctx);
    const { data, error } = await supabase.from("wallet_transactions").insert({
      student_name: studentName,
      guardian_name: guardianName ?? null,
      amount,
      kind: kind ?? "package",
      description: description ?? null
    }).select().single();
    if (error) throw databaseError(error.message);
    return textResult({ transaction: data });
  }
});

// src/lib/mcp/tools/blocks.ts
import { defineTool as defineTool8, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z7 } from "npm:zod@^4.6.2";
var listBlocks = defineTool8({
  name: "list_blocks",
  title: "Consultar bloqueios",
  description: "Lista os bloqueios de agenda vis\xEDveis ao usu\xE1rio conectado.",
  inputSchema: { teacher: z7.string().optional() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ teacher }, ctx) => {
    let request = supabaseForUser(ctx).from("blocks").select("*").order("created_at", { ascending: false });
    if (teacher) request = request.or(`teacher.eq.${teacher},teacher.eq.both`);
    const { data, error } = await request;
    if (error) throw databaseError(error.message);
    return textResult({ blocks: data ?? [] });
  }
});
var createBlock = defineTool8({
  name: "create_block",
  title: "Criar bloqueio",
  description: "Cria uma indisponibilidade pontual ou recorrente ap\xF3s confirma\xE7\xE3o do usu\xE1rio.",
  inputSchema: {
    teacher: z7.string(),
    title: z7.string(),
    blockType: z7.string(),
    weekday: z7.number().optional(),
    startTime: z7.string().optional(),
    endTime: z7.string().optional(),
    startAt: z7.string().optional(),
    endAt: z7.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (input.blockType === "recurring" && (input.weekday === void 0 || !input.startTime || !input.endTime)) {
      throw new ToolError4("Bloqueios recorrentes exigem dia da semana, in\xEDcio e fim.");
    }
    if (input.blockType === "one_off" && (!input.startAt || !input.endAt)) {
      throw new ToolError4("Bloqueios pontuais exigem data/hora inicial e final.");
    }
    const supabase = await requireAdmin(ctx);
    const { data, error } = await supabase.from("blocks").insert({
      teacher: input.teacher,
      title: input.title,
      block_type: input.blockType,
      weekday: input.weekday ?? null,
      start_time: input.startTime ?? null,
      end_time: input.endTime ?? null,
      start_at: input.startAt ?? null,
      end_at: input.endAt ?? null
    }).select().single();
    if (error) throw databaseError(error.message);
    return textResult({ block: data });
  }
});
var deleteBlock = defineTool8({
  name: "delete_block",
  title: "Excluir bloqueio",
  description: "Exclui um bloqueio de agenda ap\xF3s confirma\xE7\xE3o expl\xEDcita do usu\xE1rio.",
  inputSchema: { blockId: z7.string() },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ blockId }, ctx) => {
    const { error } = await (await requireAdmin(ctx)).from("blocks").delete().eq("id", blockId);
    if (error) throw databaseError(error.message);
    return textResult({ deleted: true, blockId });
  }
});

// src/lib/mcp/index.ts
var projectRef = "htjvaozfovfiotvkmgsx";
var mcp_default = defineMcp({
  name: "site-aulas",
  title: "Site - Aulas",
  version: "0.1.0",
  instructions: "Ferramentas do Site - Aulas para consultar e administrar alunos, professores, aulas, cobran\xE7as e bloqueios. Pe\xE7a confirma\xE7\xE3o antes de criar, alterar ou excluir dados.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_students_default,
    list_teachers_default,
    list_lessons_default,
    create_lesson_default,
    update_lesson_default,
    delete_lesson_default,
    getWalletBalance,
    addWalletCredit,
    listBlocks,
    createBlock,
    deleteBlock
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
